SportsStore/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace SportsStore.Models
{
    public class Order
    {
        [BindNever]
        public int OrderId { get; set; }

        [BindNever]
        public ICollection<CartLine> Lines { get; set; } = new List<CartLine>();

        [Required(ErrorMessage = "Please enter a name")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please enter the first address line")]
        public string? Line1 { get; set; }

        public string? Line2 { get; set; }

        public string? Line3 { get; set; }

        [Required(ErrorMessage = "Please enter a city name")]
        public string? City { get; set; }

        [Required(ErrorMessage = "Please enter a state name")]
        public string? State { get; set; }

        public string? Zip { get; set; }

        [Required(ErrorMessage = "Please enter a country name")]
        public string? Country { get; set; }

        public bool GiftWrap { get; set; }

        [BindNever]
        public bool Shipped { get; set; }
    }
}

SportsStore/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportsStore.Models
{
    public class Product
    {
        public long ProductId { get; set; }

        [Required(ErrorMessage = "Please enter a product name")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a description")]
        public string Description { get; set; } = string.Empty;

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive price")]
        [Column(TypeName = "decimal(8, 2)")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Please specify a category")]
        public string Category { get; set; } = string.Empty;
    }
}

SportsStore/Components/AdminNavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Components
{
    public class AdminNavigationMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            this.ViewBag.Selection = this.Request.Path.Value ?? "Products";

            return this.View(new string[] { "Orders", "Products" });
        }
    }
}

SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.Repository;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository orderRepository;

        private Cart cart;

        public OrderController(IOrderRepository orderRepository, Cart cart)
        {
            this.orderRepository = orderRepository;
            this.cart = cart;
        }

        public ViewResult Checkout() => this.View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (!this.cart.Lines.Any())
            {
                this.ModelState.AddModelError(string.Empty, "Sorry, your cart is empty!");
            }

            if (this.ModelState.IsValid)
            {
                order.Lines = this.cart.Lines.ToArray();
                this.orderRepository.SaveOrder(order);
                this.cart.Clear();
                return this.View("Completed", order.OrderId);
            }

            return this.View();
        }
    }
}

SportsStore/Views/Admin/Create.cshtml
@model SportsStore.Models.Product

@{
    Layout = "_AdminLayout";
}

<partial name="_Editor" model='(@Model, "primary", "Create" , "Create")' />

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

SportsStore/Views/Admin/Delete.cshtml
@model SportsStore.Models.Product

@{
    Layout = "_AdminLayout";
}

<h3 class="bg-danger text-white text-center p-1">Are you sure you want to delete this?</h3>

<partial name="_ProductInfo" model="@Model" />

<form asp-action="Delete" asp-controller="Admin" method="post">
    <input type="submit" class="btn btn-danger" value="Delete" />
    <a class="btn btn-secondary" asp-controller="Admin" asp-action="Products">Back</a>
</form>

SportsStore/Views/Admin/Details.cshtml
@model SportsStore.Models.Product?

@{
    Layout = "_AdminLayout";
}

<h3 class="bg-info text-white text-center p-1">Details</h3>

<partial name="_ProductInfo" model="@Model" />

<a class="btn btn-warning" asp-controller="Admin" asp-action="Edit" asp-route-productId="@Model?.ProductId">Edit</a>
<a class="btn btn-secondary" asp-controller="Admin" asp-action="Products">Back</a>

SportsStore/Views/Admin/Edit.cshtml
@model SportsStore.Models.Product

@{
    Layout = "_AdminLayout";
}

<partial name="_Editor" model='(@Model, "warning", "Edit" , "Edit")' />

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

SportsStore/Views/Admin/Orders.cshtml
@model IQueryable<Order>

@{
    Layout = "_AdminLayout";
    var unshippedOrders = Model.Where(o => !o.Shipped);
    var shippedOrders = Model.Where(o => o.Shipped);
}

<partial name="_OrderTable" model='(unshippedOrders, "Unshipped Orders", "Ship", "MarkShipped")' />
<partial name="_OrderTable" model='(shippedOrders, "Shipped Orders", "Reset", "Reset")' />

<form asp-action="Orders" method="post">
    <button class="btn btn-info">Refresh Data</button>
</form>

SportsStore/Views/Admin/Products.cshtml
@model IQueryable<Product>

@{
    Layout = "_AdminLayout";
}

<table class="table table-sm table-striped table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <td />
        </tr>
    </thead>
    <tbody>
        @if (Model?.Count() > 0)
        {
            @foreach (Product p in Model)
            {
                <tr>
                    <td>@p.ProductId</td>
                    <td>@p.Name</td>
                    <td>@p.Category</td>
                    <td>@p.Price.ToString("c")</td>
                    <td>
                        <a class="btn btn-info btn-sm" asp-controller="Admin" asp-action="Details" asp-route-productId="@p.ProductId">
                            Details
                        </a>
                        <a class="btn btn-warning btn-sm" asp-controller="Admin" asp-action="Edit" asp-route-productId="@p.ProductId">
                            Edit
                        </a>
                        <a class="btn btn-danger btn-sm" asp-controller="Admin" asp-action="Delete" asp-route-productId="@p.ProductId">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="5" class="text-center">No Products</td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-controller="Admin" asp-action="Create">Create</a>

SportsStore/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-info text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <span class="navbar-brand ml-2">SPORTS STORE Administration</span>
                </div>
                <div class="col-2 text-right">
                    <a class="btn btn-sm btn-primary" asp-controller="Account" asp-action="Login">Log Out</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row p-2">
            <div class="col-3">
                <vc:admin-navigation-menu />
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SportsStore/Views/Admin/_Editor.cshtml
@model (Product Product, string ThemeColor, string TitleText, string CallbackMethodName)

@{
    Product product = Model.Product;
}

<h3 class="bg-@Model.ThemeColor text-white text-center p-1">@Model.TitleText a Product</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="@Model.CallbackMethodName" asp-controller="Admin" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (product.ProductId != 0)
            {
                <div class="form-group">
                    <label asp-for="@product.ProductId" class="control-label"></label>
                    <input asp-for="@product.ProductId" class="form-control" readonly />
                </div>
            }
            <div class="form-group">
                <label asp-for="@product.Name" class="control-label"></label>
                <input asp-for="@product.Name" class="form-control" />
                <span asp-validation-for="@product.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@product.Description" class="control-label"></label>
                <input asp-for="@product.Description" class="form-control" />
                <span asp-validation-for="@product.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@product.Price" class="control-label"></label>
                <input asp-for="@product.Price" class="form-control" />
                <span asp-validation-for="@product.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@product.Category" class="control-label"></label>
                <input asp-for="@product.Category" class="form-control" />
                <span asp-validation-for="@product.Category" class="text-danger"></span>
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-@Model.ThemeColor">Save</button>
                <a class="btn btn-secondary" asp-controller="Admin" asp-action="Products">Cancel</a>
            </div>
        </form>
    </div>
</div>

SportsStore/Views/Admin/_OrderTable.cshtml
@model (IQueryable<Order> Orders, string TableTitle, string ButtonLabel, string CallbackMethodName)

<table class="table table-sm table-striped table-bordered">
    <thead>
        <tr><th colspan="5" class="text-center">@Model.TableTitle</th></tr>
    </thead>
    <tbody>
        @if (Model.Orders.Any())
        {
            @foreach (Order o in Model.Orders)
            {
                <tr>
                    <td>@o.Name</td>
                    <td>@o.Zip</td>
                    <th>Product</th>
                    <th>Quantity</th>
                    <td>
                        <form asp-action=@Model.CallbackMethodName method="post">
                            <input type="hidden" name="OrderId" value="@o.OrderId" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                @Model.ButtonLabel
                            </button>
                        </form>
                    </td>
                </tr>
                @foreach (CartLine line in o.Lines)
                {
                    <tr>
                        <td colspan="2"></td>
                        <td>@line.Product.Name</td>
                        <td>@line.Quantity</td>
                        <td></td>
                    </tr>
                }
            }
        }
        else
        {
            <tr><td colspan="5" class="text-center">No Orders</td></tr>
        }
    </tbody>
</table>

SportsStore/Views/Admin/_ProductInfo.cshtml
@model SportsStore.Models.Product?

<table class="table table-sm table-bordered table-striped">
    <tbody>
        <tr>
            <th>Id</th>
            <td>@Model?.ProductId</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>@Model?.Name</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>@Model?.Description</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>@Model?.Category</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>@Model?.Price.ToString("C")</td>
        </tr>
    </tbody>
</table>